# Generated by Django 5.0.3 on 2024-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, verbose_name='Category designation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='plantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plantes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plantes%Y/%m/%d', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('medecinal_benifit', models.TextField(verbose_name='Medecinal benefit')),
                ('use', models.TextField(verbose_name='How use')),
                ('culture', models.TextField(verbose_name='Culture')),
                ('source', models.URLField(verbose_name='Source')),
            ],
        ),
    ]
